"""
Seed database with jazz-themed sample data for development and testing.
Techs are jazz musicians, jobs are concert venue gigs.

v0.0.8 — 25 technicians and 50 jobs with deliberately varied
speed_factor and skill_bonuses for the duration sampler / ML demo.

These performance modifiers are GROUND TRUTH attributes hidden from the
dispatcher view. The router doesn't see them. The duration sampler uses
them to produce realistic actual_duration_minutes. God View reveals them
during the demo to make the "ML will learn this" pitch legible.

In production, new technicians enter with speed_factor=1.0 and
skill_bonuses={} (model defaults). The values evolve only through the
ML model observing actual_duration_minutes over time. The dispatcher
never types these values into a form — they are write-only-by-system.

Management Areas:
MN-DOWNTOWN  — Lower Manhattan (below 14th St)
MN-MIDTOWN   — Midtown Manhattan (14th–59th St)
MN-WEST      — Upper West Side (59th–110th St west)
MN-EAST      — Upper East Side (59th–110th St east)
MN-HARLEM    — Harlem / Washington Heights (110th+ St)
MN-WASH-HTS  — Washington Heights (155th+ St)
BK-NORTH     — North Brooklyn (Williamsburg, Greenpoint, DUMBO)
BK-WEST      — West Brooklyn (Cobble Hill, Park Slope, Red Hook)
BK-SOUTH     — South Brooklyn (Flatbush, Midwood)
BK-EAST      — East Brooklyn (Bed-Stuy, Bushwick, East NY)
QN-SOUTH     — South Queens (Jamaica, Far Rockaway)
QN-CENTRAL   — Central Queens (Flushing, Forest Hills)
BX-SOUTH     — South Bronx

Usage:
python -m backend.database.seeds.seed_data
"""
import asyncio
from datetime import datetime, timedelta, timezone

from backend.database.connection import AsyncSessionLocal, init_db
from backend.database.models import Technician, Job, Assignment, TechnicianStatus, JobStatus, JobType

# speed_factor: global multiplier on sampled durations (1.0 = nominal)
# skill_bonuses: per-job-type multiplier, stacks with speed_factor
# final_multiplier = speed_factor * skill_bonuses.get(job_type, 1.0)

TECHNICIANS = [
	# ── The Fast Senior — Miles Davis (0.80) ──
	{
		"name": "Miles Davis",
		"employee_id": "MD001",
		"phone": "555-0101",
		"email": "miles@fieldopt.com",
		"home_latitude": 40.7831,
		"home_longitude": -73.9712,
		"home_address": "Upper West Side, Manhattan",
		"skills": ["install", "repair", "maintenance", "service_change"],
		"assigned_routes": ["MN-WEST", "MN-MIDTOWN"],
		"shift_start": "08:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 10,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.80,
		"skill_bonuses": {"install": 0.85, "service_change": 0.90},
	},
	# ── Solidly Above — John Coltrane (0.92) ──
	{
		"name": "John Coltrane",
		"employee_id": "JC003",
		"phone": "555-0103",
		"email": "coltrane@fieldopt.com",
		"home_latitude": 40.6892,
		"home_longitude": -73.9857,
		"home_address": "Cobble Hill, Brooklyn",
		"skills": ["install", "repair", "maintenance", "inspection", "service_change"],
		"assigned_routes": ["BK-NORTH", "BK-WEST"],
		"shift_start": "08:00",
		"shift_end": "18:00",
		"max_jobs_per_day": 10,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.92,
		"skill_bonuses": {},
	},
	# ── Solidly Above — Charles Mingus (0.90) ──
	{
		"name": "Charles Mingus",
		"employee_id": "CM005",
		"phone": "555-0105",
		"email": "mingus@fieldopt.com",
		"home_latitude": 40.6501,
		"home_longitude": -73.9496,
		"home_address": "Flatbush, Brooklyn",
		"skills": ["install", "disconnect", "service_change"],
		"assigned_routes": ["BK-SOUTH", "BK-EAST"],
		"shift_start": "07:00",
		"shift_end": "15:00",
		"max_jobs_per_day": 9,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.90,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Chet Baker (1.02) ──
	{
		"name": "Chet Baker",
		"employee_id": "CB002",
		"phone": "555-0102",
		"email": "chet@fieldopt.com",
		"home_latitude": 40.7282,
		"home_longitude": -73.7949,
		"home_address": "Jamaica, Queens",
		"skills": ["install", "repair", "disconnect", "inspection"],
		"assigned_routes": ["QN-SOUTH", "QN-CENTRAL"],
		"shift_start": "07:00",
		"shift_end": "16:00",
		"max_jobs_per_day": 7,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.02,
		"skill_bonuses": {},
	},
	# ── Slightly Slow — Thelonious Monk (1.10) ──
	{
		"name": "Thelonious Monk",
		"employee_id": "TM004",
		"phone": "555-0104",
		"email": "monk@fieldopt.com",
		"home_latitude": 40.8116,
		"home_longitude": -73.9465,
		"home_address": "Harlem, Manhattan",
		"skills": ["repair", "maintenance", "inspection"],
		"assigned_routes": ["MN-HARLEM", "MN-WASH-HTS"],
		"shift_start": "09:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 6,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.10,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Ella Fitzgerald (0.98) ──
	{
		"name": "Ella Fitzgerald",
		"employee_id": "EF006",
		"phone": "555-0106",
		"email": "ella@fieldopt.com",
		"home_latitude": 40.7527,
		"home_longitude": -73.9772,
		"home_address": "Midtown East, Manhattan",
		"skills": ["install", "repair", "maintenance", "disconnect"],
		"assigned_routes": ["MN-MIDTOWN", "MN-EAST"],
		"shift_start": "08:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 9,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.98,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Dizzy Gillespie (1.00) — Bronx generalist ──
	{
		"name": "Dizzy Gillespie",
		"employee_id": "DG007",
		"phone": "555-0107",
		"email": "dizzy@fieldopt.com",
		"home_latitude": 40.8296,
		"home_longitude": -73.9262,
		"home_address": "South Bronx, Bronx",
		"skills": ["install", "repair", "maintenance", "inspection", "service_change"],
		"assigned_routes": ["BX-SOUTH", "MN-HARLEM"],
		"shift_start": "08:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 8,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.00,
		"skill_bonuses": {},
	},
	# ── Specialist — John Zorn (0.88) — repair fast, install slow ──
	# Pitch story: router gives Zorn installs because he's fast in general;
	# God View shows he's actually slow on them.
	{
		"name": "John Zorn",
		"employee_id": "JZ008",
		"phone": "555-0108",
		"email": "zorn@fieldopt.com",
		"home_latitude": 40.7185,
		"home_longitude": -73.9868,
		"home_address": "Lower East Side, Manhattan",
		"skills": ["install", "repair", "maintenance", "service_change", "inspection", "disconnect"],
		"assigned_routes": ["MN-DOWNTOWN", "MN-EAST"],
		"shift_start": "10:00",
		"shift_end": "19:00",
		"max_jobs_per_day": 7,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.88,
		"skill_bonuses": {"repair": 0.80, "install": 1.20},
	},
	# ── Near Nominal — Billie Holiday (1.05) — starts off-duty ──
	{
		"name": "Billie Holiday",
		"employee_id": "BH009",
		"phone": "555-0109",
		"email": "billie@fieldopt.com",
		"home_latitude": 40.7614,
		"home_longitude": -73.9776,
		"home_address": "5th Ave, Manhattan",
		"skills": ["install", "repair", "disconnect"],
		"assigned_routes": ["MN-MIDTOWN", "MN-WEST"],
		"shift_start": "08:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 8,
		"status": TechnicianStatus.OFF_DUTY,
		"speed_factor": 1.05,
		"skill_bonuses": {},
	},
	# ── Solidly Above — Art Blakey (0.93) ──
	{
		"name": "Art Blakey",
		"employee_id": "AB010",
		"phone": "555-0110",
		"email": "blakey@fieldopt.com",
		"home_latitude": 40.6872,
		"home_longitude": -73.9418,
		"home_address": "Bedford-Stuyvesant, Brooklyn",
		"skills": ["install", "maintenance", "repair", "disconnect", "service_change"],
		"assigned_routes": ["BK-NORTH", "BK-EAST"],
		"shift_start": "06:00",
		"shift_end": "15:00",
		"max_jobs_per_day": 10,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.93,
		"skill_bonuses": {},
	},
	# ── The Slow Green — Mary Halvorson (1.25) ──
	# New hire, still learning. When ML lands, the model "promotes" her as she improves.
	{
		"name": "Mary Halvorson",
		"employee_id": "MH011",
		"phone": "555-0111",
		"email": "halvorson@fieldopt.com",
		"home_latitude": 40.7081,
		"home_longitude": -73.9571,
		"home_address": "Williamsburg, Brooklyn",
		"skills": ["install", "repair", "maintenance"],
		"assigned_routes": ["BK-NORTH"],
		"shift_start": "09:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 5,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.25,
		"skill_bonuses": {},
	},
	# ── Slightly Slow — Sun Ra (1.15) — catastrophic on service_change ──
	# Dramatic God View reveal: 1.15 * 1.40 = 1.61 effective on service_change.
	{
		"name": "Sun Ra",
		"employee_id": "SR012",
		"phone": "555-0112",
		"email": "sunra@fieldopt.com",
		"home_latitude": 40.6782,
		"home_longitude": -73.9442,
		"home_address": "Crown Heights, Brooklyn",
		"skills": ["install", "repair", "maintenance", "service_change"],
		"assigned_routes": ["BK-EAST", "BK-SOUTH"],
		"shift_start": "10:00",
		"shift_end": "18:00",
		"max_jobs_per_day": 6,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.15,
		"skill_bonuses": {"service_change": 1.40},
	},
	# ── Specialist — Alice Coltrane (1.03) — maintenance/inspection fast, install slow ──
	{
		"name": "Alice Coltrane",
		"employee_id": "AC013",
		"phone": "555-0113",
		"email": "alice@fieldopt.com",
		"home_latitude": 40.6921,
		"home_longitude": -73.9890,
		"home_address": "Park Slope, Brooklyn",
		"skills": ["install", "repair", "maintenance", "inspection"],
		"assigned_routes": ["BK-WEST", "BK-NORTH"],
		"shift_start": "08:00",
		"shift_end": "16:00",
		"max_jobs_per_day": 8,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.03,
		"skill_bonuses": {"maintenance": 0.85, "inspection": 0.85, "install": 1.10},
	},
	# ── Near Nominal — Ornette Coleman (0.95) ──
	{
		"name": "Ornette Coleman",
		"employee_id": "OC014",
		"phone": "555-0114",
		"email": "ornette@fieldopt.com",
		"home_latitude": 40.7351,
		"home_longitude": -73.9890,
		"home_address": "Greenwich Village, Manhattan",
		"skills": ["install", "repair", "maintenance"],
		"assigned_routes": ["MN-DOWNTOWN", "MN-MIDTOWN"],
		"shift_start": "08:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 8,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.95,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Eric Dolphy (0.97) ──
	{
		"name": "Eric Dolphy",
		"employee_id": "ED015",
		"phone": "555-0115",
		"email": "dolphy@fieldopt.com",
		"home_latitude": 40.7748,
		"home_longitude": -73.9596,
		"home_address": "Upper East Side, Manhattan",
		"skills": ["install", "repair", "inspection"],
		"assigned_routes": ["MN-EAST", "MN-MIDTOWN"],
		"shift_start": "08:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 8,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.97,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Pharoah Sanders (0.93) ──
	{
		"name": "Pharoah Sanders",
		"employee_id": "PS016",
		"phone": "555-0116",
		"email": "pharoah@fieldopt.com",
		"home_latitude": 40.8244,
		"home_longitude": -73.9446,
		"home_address": "Hamilton Heights, Manhattan",
		"skills": ["install", "repair", "service_change"],
		"assigned_routes": ["MN-HARLEM", "MN-WASH-HTS"],
		"shift_start": "07:00",
		"shift_end": "16:00",
		"max_jobs_per_day": 9,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.93,
		"skill_bonuses": {},
	},
	# ── Slightly Slow — Albert Ayler (1.08) ──
	{
		"name": "Albert Ayler",
		"employee_id": "AA017",
		"phone": "555-0117",
		"email": "ayler@fieldopt.com",
		"home_latitude": 40.7589,
		"home_longitude": -73.9851,
		"home_address": "Hell's Kitchen, Manhattan",
		"skills": ["repair", "maintenance", "disconnect"],
		"assigned_routes": ["MN-MIDTOWN", "MN-WEST"],
		"shift_start": "10:00",
		"shift_end": "18:00",
		"max_jobs_per_day": 6,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.08,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Cecil Taylor (1.07) ──
	{
		"name": "Cecil Taylor",
		"employee_id": "CT018",
		"phone": "555-0118",
		"email": "cecil@fieldopt.com",
		"home_latitude": 40.7281,
		"home_longitude": -73.7949,
		"home_address": "Jamaica, Queens",
		"skills": ["install", "repair", "maintenance"],
		"assigned_routes": ["QN-SOUTH", "QN-CENTRAL"],
		"shift_start": "09:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 7,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.07,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Don Cherry (0.96) ──
	{
		"name": "Don Cherry",
		"employee_id": "DC019",
		"phone": "555-0119",
		"email": "cherry@fieldopt.com",
		"home_latitude": 40.7661,
		"home_longitude": -73.9182,
		"home_address": "Astoria, Queens",
		"skills": ["install", "repair", "inspection", "disconnect", "service_change"],
		"assigned_routes": ["QN-CENTRAL", "MN-EAST"],
		"shift_start": "08:00",
		"shift_end": "16:00",
		"max_jobs_per_day": 8,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.96,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Anthony Braxton (1.04) ──
	{
		"name": "Anthony Braxton",
		"employee_id": "AB020",
		"phone": "555-0120",
		"email": "braxton@fieldopt.com",
		"home_latitude": 40.8290,
		"home_longitude": -73.9220,
		"home_address": "Mott Haven, Bronx",
		"skills": ["install", "repair", "maintenance", "inspection", "service_change"],
		"assigned_routes": ["BX-SOUTH", "MN-HARLEM"],
		"shift_start": "07:00",
		"shift_end": "16:00",
		"max_jobs_per_day": 8,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.04,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Tim Berne (1.01) ──
	{
		"name": "Tim Berne",
		"employee_id": "TB021",
		"phone": "555-0121",
		"email": "berne@fieldopt.com",
		"home_latitude": 40.7044,
		"home_longitude": -73.9067,
		"home_address": "Bushwick, Brooklyn",
		"skills": ["repair", "maintenance", "service_change"],
		"assigned_routes": ["BK-EAST", "BK-NORTH"],
		"shift_start": "09:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 7,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.01,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Henry Threadgill (0.94) ──
	{
		"name": "Henry Threadgill",
		"employee_id": "HT022",
		"phone": "555-0122",
		"email": "threadgill@fieldopt.com",
		"home_latitude": 40.6486,
		"home_longitude": -73.9614,
		"home_address": "Midwood, Brooklyn",
		"skills": ["install", "repair", "maintenance", "disconnect", "inspection"],
		"assigned_routes": ["BK-SOUTH", "BK-WEST"],
		"shift_start": "08:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 9,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.94,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Matana Roberts (1.06) ──
	{
		"name": "Matana Roberts",
		"employee_id": "MR023",
		"phone": "555-0123",
		"email": "matana@fieldopt.com",
		"home_latitude": 40.7128,
		"home_longitude": -74.0060,
		"home_address": "Tribeca, Manhattan",
		"skills": ["install", "repair", "inspection"],
		"assigned_routes": ["MN-DOWNTOWN"],
		"shift_start": "08:00",
		"shift_end": "16:00",
		"max_jobs_per_day": 7,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.06,
		"skill_bonuses": {},
	},
	# ── Near Nominal — Jaimie Branch (0.99) ──
	{
		"name": "Jaimie Branch",
		"employee_id": "JB024",
		"phone": "555-0124",
		"email": "jaimie@fieldopt.com",
		"home_latitude": 40.6943,
		"home_longitude": -73.9249,
		"home_address": "Bed-Stuy, Brooklyn",
		"skills": ["install", "repair", "maintenance", "service_change"],
		"assigned_routes": ["BK-EAST", "BK-NORTH"],
		"shift_start": "08:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 8,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 0.99,
		"skill_bonuses": {},
	},
	# ── True Nominal — Mary Lou Williams (1.00) — calibration baseline ──
	{
		"name": "Mary Lou Williams",
		"employee_id": "MW025",
		"phone": "555-0125",
		"email": "marylou@fieldopt.com",
		"home_latitude": 40.8084,
		"home_longitude": -73.9476,
		"home_address": "Sugar Hill, Manhattan",
		"skills": ["install", "repair", "maintenance", "inspection", "disconnect"],
		"assigned_routes": ["MN-HARLEM", "MN-WEST"],
		"shift_start": "08:00",
		"shift_end": "17:00",
		"max_jobs_per_day": 9,
		"status": TechnicianStatus.AVAILABLE,
		"speed_factor": 1.00,
		"skill_bonuses": {},
	},
]


def make_jobs():
	"""
	Generate 50 jobs distributed across NYC management areas.

	Distribution:
	  Manhattan (5 areas): ~24 jobs
	  Brooklyn  (4 areas): ~14 jobs
	  Queens    (2 areas):  ~7 jobs
	  Bronx     (1 area):   ~5 jobs
	  Tomorrow:             5 jobs (for day-picker demo)

	NOTE: datetime.now() here is intentional — seed data needs real wall-clock
	time so today's jobs land on actual today, not simulated time.
	"""
	today = datetime.now(timezone.utc).replace(hour=8, minute=0, second=0, microsecond=0)
	tomorrow = today + timedelta(days=1)

	return [
		# ─── MANHATTAN — DOWNTOWN (8 jobs) ───
		{
			"customer_name": "Blue Note Jazz Club",
			"service_address": "131 W 3rd St",
			"service_city": "New York",
			"service_zip": "10012",
			"latitude": 40.7308,
			"longitude": -73.9973,
			"job_type": JobType.INSTALL,
			"required_skills": ["install"],
			"route_criteria": "MN-DOWNTOWN",
			"priority": 1,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 90,
			"description": "Sound system install — main stage",
		},
		{
			"customer_name": "Village Vanguard",
			"service_address": "178 7th Ave S",
			"service_city": "New York",
			"service_zip": "10014",
			"latitude": 40.7359,
			"longitude": -74.0014,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "MN-DOWNTOWN",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 60,
			"description": "Stage monitor repair — intermittent signal",
		},
		{
			"customer_name": "Smalls Jazz Club",
			"service_address": "183 W 10th St",
			"service_city": "New York",
			"service_zip": "10014",
			"latitude": 40.7337,
			"longitude": -74.0023,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair", "maintenance"],
			"route_criteria": "MN-DOWNTOWN",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Mixing console channel 7-8 dead — needs trace",
		},
		{
			"customer_name": "The Stone at New School",
			"service_address": "55 W 13th St",
			"service_city": "New York",
			"service_zip": "10011",
			"latitude": 40.7365,
			"longitude": -73.9960,
			"job_type": JobType.DISCONNECT,
			"required_skills": ["disconnect"],
			"route_criteria": "MN-DOWNTOWN",
			"priority": 4,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 30,
			"description": "Remove old analog board — prep for digital upgrade",
		},
		{
			"customer_name": "Zinc Bar",
			"service_address": "82 W 3rd St",
			"service_city": "New York",
			"service_zip": "10012",
			"latitude": 40.7300,
			"longitude": -73.9990,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "MN-DOWNTOWN",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Subwoofer rattling — likely blown driver",
		},
		{
			"customer_name": "Le Poisson Rouge",
			"service_address": "158 Bleecker St",
			"service_city": "New York",
			"service_zip": "10012",
			"latitude": 40.7283,
			"longitude": -74.0002,
			"job_type": JobType.SERVICE_CHANGE,
			"required_skills": ["service_change", "repair"],
			"route_criteria": "MN-DOWNTOWN",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 90,
			"description": "FOH board output bus failure — swap needed",
		},
		{
			"customer_name": "SOB's",
			"service_address": "204 Varick St",
			"service_city": "New York",
			"service_zip": "10014",
			"latitude": 40.7274,
			"longitude": -74.0057,
			"job_type": JobType.INSTALL,
			"required_skills": ["install"],
			"route_criteria": "MN-DOWNTOWN",
			"priority": 4,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "17:00",
			"estimated_duration": 60,
			"description": "Install backup DI box rack — stage left",
		},
		{
			"customer_name": "Mezzrow Jazz Club",
			"service_address": "163 W 10th St",
			"service_city": "New York",
			"service_zip": "10014",
			"latitude": 40.7340,
			"longitude": -74.0020,
			"job_type": JobType.INSPECTION,
			"required_skills": ["inspection"],
			"route_criteria": "MN-DOWNTOWN",
			"priority": 5,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 30,
			"description": "Routine wiring inspection — basement venue",
		},

		# ─── MANHATTAN — MIDTOWN (7 jobs) ───
		{
			"customer_name": "Birdland Jazz Club",
			"service_address": "315 W 44th St",
			"service_city": "New York",
			"service_zip": "10036",
			"latitude": 40.7590,
			"longitude": -73.9905,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance"],
			"route_criteria": "MN-MIDTOWN",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Quarterly PA system maintenance",
		},
		{
			"customer_name": "Iridium Jazz Club",
			"service_address": "1650 Broadway",
			"service_city": "New York",
			"service_zip": "10019",
			"latitude": 40.7610,
			"longitude": -73.9842,
			"job_type": JobType.INSTALL,
			"required_skills": ["install", "repair"],
			"route_criteria": "MN-MIDTOWN",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 75,
			"description": "Replace front-of-house mic stands and cable runs",
		},
		{
			"customer_name": "Town Hall",
			"service_address": "123 W 43rd St",
			"service_city": "New York",
			"service_zip": "10036",
			"latitude": 40.7560,
			"longitude": -73.9847,
			"job_type": JobType.SERVICE_CHANGE,
			"required_skills": ["service_change"],
			"route_criteria": "MN-MIDTOWN",
			"priority": 1,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 120,
			"description": "Upgrade dimmer rack — historic theater",
			"special_instructions": "VIP venue — coordinate with house manager",
		},
		{
			"customer_name": "Carnegie Hall",
			"service_address": "881 7th Ave",
			"service_city": "New York",
			"service_zip": "10019",
			"latitude": 40.7651,
			"longitude": -73.9799,
			"job_type": JobType.INSPECTION,
			"required_skills": ["inspection"],
			"route_criteria": "MN-MIDTOWN",
			"priority": 1,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 60,
			"description": "Annual stage rigging inspection — main hall",
			"special_instructions": "VIP venue — full security clearance required",
		},
		{
			"customer_name": "Beacon Theatre",
			"service_address": "2124 Broadway",
			"service_city": "New York",
			"service_zip": "10023",
			"latitude": 40.7800,
			"longitude": -73.9819,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "MN-MIDTOWN",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 60,
			"description": "House left line array — channel 3 cutting out",
		},
		{
			"customer_name": "Radio City Music Hall",
			"service_address": "1260 6th Ave",
			"service_city": "New York",
			"service_zip": "10020",
			"latitude": 40.7600,
			"longitude": -73.9800,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance"],
			"route_criteria": "MN-MIDTOWN",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 60,
			"description": "Monthly preventive maintenance — main console",
		},
		{
			"customer_name": "The Cutting Room",
			"service_address": "44 E 32nd St",
			"service_city": "New York",
			"service_zip": "10016",
			"latitude": 40.7456,
			"longitude": -73.9836,
			"job_type": JobType.DISCONNECT,
			"required_skills": ["disconnect"],
			"route_criteria": "MN-MIDTOWN",
			"priority": 4,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 30,
			"description": "Remove decommissioned wireless mic system",
		},

		# ─── MANHATTAN — WEST (4 jobs) ───
		{
			"customer_name": "Jazz at Lincoln Center",
			"service_address": "10 Columbus Cir",
			"service_city": "New York",
			"service_zip": "10019",
			"latitude": 40.7688,
			"longitude": -73.9830,
			"job_type": JobType.INSTALL,
			"required_skills": ["install", "service_change"],
			"route_criteria": "MN-WEST",
			"priority": 1,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 120,
			"description": "New wireless mic system — Rose Theater",
			"special_instructions": "VIP venue — coordinate with house manager",
		},
		{
			"customer_name": "Dizzy's Club",
			"service_address": "10 Columbus Cir, 5th Fl",
			"service_city": "New York",
			"service_zip": "10019",
			"latitude": 40.7686,
			"longitude": -73.9828,
			"job_type": JobType.INSPECTION,
			"required_skills": ["inspection"],
			"route_criteria": "MN-WEST",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "17:00",
			"estimated_duration": 30,
			"description": "Annual safety inspection — stage rigging",
		},
		{
			"customer_name": "Symphony Space",
			"service_address": "2537 Broadway",
			"service_city": "New York",
			"service_zip": "10025",
			"latitude": 40.7975,
			"longitude": -73.9712,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "MN-WEST",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 60,
			"description": "Stage left house cluster — phase issues",
		},
		{
			"customer_name": "Cleopatra's Needle",
			"service_address": "2485 Broadway",
			"service_city": "New York",
			"service_zip": "10025",
			"latitude": 40.7956,
			"longitude": -73.9722,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance"],
			"route_criteria": "MN-WEST",
			"priority": 4,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Replace worn XLR cables on stage",
		},

		# ─── MANHATTAN — EAST (2 jobs) ───
		{
			"customer_name": "92nd Street Y",
			"service_address": "1395 Lexington Ave",
			"service_city": "New York",
			"service_zip": "10128",
			"latitude": 40.7831,
			"longitude": -73.9509,
			"job_type": JobType.INSTALL,
			"required_skills": ["install"],
			"route_criteria": "MN-EAST",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 90,
			"description": "Install new lectern mic + recording feed",
		},
		{
			"customer_name": "Cafe Carlyle",
			"service_address": "35 E 76th St",
			"service_city": "New York",
			"service_zip": "10021",
			"latitude": 40.7745,
			"longitude": -73.9628,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "MN-EAST",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 60,
			"description": "Piano mic preamp distortion — investigate",
		},

		# ─── MANHATTAN — HARLEM (3 jobs) ───
		{
			"customer_name": "Minton's Playhouse",
			"service_address": "206 W 118th St",
			"service_city": "New York",
			"service_zip": "10026",
			"latitude": 40.8039,
			"longitude": -73.9541,
			"job_type": JobType.INSTALL,
			"required_skills": ["install", "repair"],
			"route_criteria": "MN-HARLEM",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 90,
			"description": "Stage lighting control install + existing dimmer repair",
		},
		{
			"customer_name": "Apollo Theater",
			"service_address": "253 W 125th St",
			"service_city": "New York",
			"service_zip": "10027",
			"latitude": 40.8100,
			"longitude": -73.9500,
			"job_type": JobType.SERVICE_CHANGE,
			"required_skills": ["service_change", "install"],
			"route_criteria": "MN-HARLEM",
			"priority": 1,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 120,
			"description": "Upgrade house sound from analog to digital snake",
			"special_instructions": "Load-in door on 126th — call house audio",
		},
		{
			"customer_name": "Showman's Jazz Club",
			"service_address": "375 W 125th St",
			"service_city": "New York",
			"service_zip": "10027",
			"latitude": 40.8118,
			"longitude": -73.9530,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance"],
			"route_criteria": "MN-HARLEM",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Replace house compressor — old unit failing intermittently",
		},

		# ─── BROOKLYN — NORTH (5 jobs) ───
		{
			"customer_name": "Brooklyn Bowl",
			"service_address": "61 Wythe Ave",
			"service_city": "Brooklyn",
			"service_zip": "11249",
			"latitude": 40.7188,
			"longitude": -73.9618,
			"job_type": JobType.INSTALL,
			"required_skills": ["install", "maintenance"],
			"route_criteria": "BK-NORTH",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 90,
			"description": "New monitor wedge install — 6 positions",
		},
		{
			"customer_name": "National Sawdust",
			"service_address": "80 N 6th St",
			"service_city": "Brooklyn",
			"service_zip": "11249",
			"latitude": 40.7182,
			"longitude": -73.9621,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance", "inspection"],
			"route_criteria": "BK-NORTH",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "17:00",
			"estimated_duration": 60,
			"description": "Semi-annual acoustic panel inspection + cleaning",
		},
		{
			"customer_name": "Music Hall of Williamsburg",
			"service_address": "66 N 6th St",
			"service_city": "Brooklyn",
			"service_zip": "11249",
			"latitude": 40.7180,
			"longitude": -73.9619,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "BK-NORTH",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 60,
			"description": "Subwoofer cabinet — buzz at low frequencies",
		},
		{
			"customer_name": "Baby's All Right",
			"service_address": "146 Broadway",
			"service_city": "Brooklyn",
			"service_zip": "11211",
			"latitude": 40.7100,
			"longitude": -73.9650,
			"job_type": JobType.INSTALL,
			"required_skills": ["install"],
			"route_criteria": "BK-NORTH",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 75,
			"description": "Install new green room speaker system",
		},
		{
			"customer_name": "Union Pool",
			"service_address": "484 Union Ave",
			"service_city": "Brooklyn",
			"service_zip": "11211",
			"latitude": 40.7129,
			"longitude": -73.9510,
			"job_type": JobType.DISCONNECT,
			"required_skills": ["disconnect"],
			"route_criteria": "BK-NORTH",
			"priority": 5,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 30,
			"description": "Remove obsolete patch bay",
		},

		# ─── BROOKLYN — WEST (3 jobs) ───
		{
			"customer_name": "Barbès",
			"service_address": "376 9th St",
			"service_city": "Brooklyn",
			"service_zip": "11215",
			"latitude": 40.6700,
			"longitude": -73.9818,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance"],
			"route_criteria": "BK-WEST",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 45,
			"description": "Quarterly back-room PA tuning",
		},
		{
			"customer_name": "Sunny's Bar",
			"service_address": "253 Conover St",
			"service_city": "Brooklyn",
			"service_zip": "11231",
			"latitude": 40.6770,
			"longitude": -74.0140,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "BK-WEST",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 60,
			"description": "Stage box loose connection — full reseat",
		},
		{
			"customer_name": "Bell House",
			"service_address": "149 7th St",
			"service_city": "Brooklyn",
			"service_zip": "11215",
			"latitude": 40.6735,
			"longitude": -73.9851,
			"job_type": JobType.INSTALL,
			"required_skills": ["install"],
			"route_criteria": "BK-WEST",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 90,
			"description": "Add second wireless receiver rack — capacity expansion",
		},

		# ─── BROOKLYN — SOUTH (3 jobs) ───
		{
			"customer_name": "Kings Theatre",
			"service_address": "1027 Flatbush Ave",
			"service_city": "Brooklyn",
			"service_zip": "11226",
			"latitude": 40.6500,
			"longitude": -73.9580,
			"job_type": JobType.SERVICE_CHANGE,
			"required_skills": ["service_change"],
			"route_criteria": "BK-SOUTH",
			"priority": 1,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 120,
			"description": "Replace house mixing position — old console retired",
			"special_instructions": "Historic theater — no drilling without approval",
		},
		{
			"customer_name": "Brooklyn College Center",
			"service_address": "2900 Bedford Ave",
			"service_city": "Brooklyn",
			"service_zip": "11210",
			"latitude": 40.6312,
			"longitude": -73.9525,
			"job_type": JobType.INSPECTION,
			"required_skills": ["inspection"],
			"route_criteria": "BK-SOUTH",
			"priority": 4,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Semester-end equipment inspection",
		},
		{
			"customer_name": "Flatbush Caton Market",
			"service_address": "794 Flatbush Ave",
			"service_city": "Brooklyn",
			"service_zip": "11226",
			"latitude": 40.6520,
			"longitude": -73.9590,
			"job_type": JobType.INSTALL,
			"required_skills": ["install"],
			"route_criteria": "BK-SOUTH",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 60,
			"description": "Mount overhead speakers in new event space",
		},

		# ─── BROOKLYN — EAST (3 jobs) ───
		{
			"customer_name": "House of Yes",
			"service_address": "2 Wyckoff Ave",
			"service_city": "Brooklyn",
			"service_zip": "11237",
			"latitude": 40.7060,
			"longitude": -73.9230,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair", "service_change"],
			"route_criteria": "BK-EAST",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 75,
			"description": "DJ booth output channel intermittent — full diag",
		},
		{
			"customer_name": "Elsewhere",
			"service_address": "599 Johnson Ave",
			"service_city": "Brooklyn",
			"service_zip": "11237",
			"latitude": 40.7081,
			"longitude": -73.9234,
			"job_type": JobType.INSTALL,
			"required_skills": ["install", "maintenance"],
			"route_criteria": "BK-EAST",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 90,
			"description": "Install rooftop stage monitor system",
		},
		{
			"customer_name": "C'mon Everybody",
			"service_address": "325 Franklin Ave",
			"service_city": "Brooklyn",
			"service_zip": "11238",
			"latitude": 40.6856,
			"longitude": -73.9569,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance"],
			"route_criteria": "BK-EAST",
			"priority": 4,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Annual PA wipedown + connector check",
		},

		# ─── QUEENS — SOUTH (3 jobs) ───
		{
			"customer_name": "Jamaica Performing Arts Center",
			"service_address": "153-10 Jamaica Ave",
			"service_city": "Queens",
			"service_zip": "11432",
			"latitude": 40.7026,
			"longitude": -73.7993,
			"job_type": JobType.INSTALL,
			"required_skills": ["install"],
			"route_criteria": "QN-SOUTH",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 90,
			"description": "Install new lobby distributed audio",
		},
		{
			"customer_name": "Resorts World NYC",
			"service_address": "110-00 Rockaway Blvd",
			"service_city": "Queens",
			"service_zip": "11420",
			"latitude": 40.6700,
			"longitude": -73.8330,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "QN-SOUTH",
			"priority": 1,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 60,
			"description": "Event hall — left side feedback issue, urgent",
		},
		{
			"customer_name": "York College Performing Arts",
			"service_address": "94-20 Guy R Brewer Blvd",
			"service_city": "Queens",
			"service_zip": "11451",
			"latitude": 40.7011,
			"longitude": -73.7954,
			"job_type": JobType.INSPECTION,
			"required_skills": ["inspection"],
			"route_criteria": "QN-SOUTH",
			"priority": 4,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Pre-semester equipment certification",
		},

		# ─── QUEENS — CENTRAL (4 jobs) ───
		{
			"customer_name": "Flushing Town Hall",
			"service_address": "137-35 Northern Blvd",
			"service_city": "Queens",
			"service_zip": "11354",
			"latitude": 40.7634,
			"longitude": -73.8273,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance"],
			"route_criteria": "QN-CENTRAL",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 60,
			"description": "Quarterly main hall PA tune-up",
		},
		{
			"customer_name": "Queens Theatre",
			"service_address": "14 United Nations Ave",
			"service_city": "Queens",
			"service_zip": "11368",
			"latitude": 40.7449,
			"longitude": -73.8453,
			"job_type": JobType.INSTALL,
			"required_skills": ["install", "service_change"],
			"route_criteria": "QN-CENTRAL",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 120,
			"description": "Studio theater — new full mic locker + cable infrastructure",
		},
		{
			"customer_name": "Forest Hills Stadium",
			"service_address": "1 Tennis Pl",
			"service_city": "Queens",
			"service_zip": "11375",
			"latitude": 40.7178,
			"longitude": -73.8444,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "QN-CENTRAL",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 75,
			"description": "Outdoor delay tower — weatherproofing failure",
		},
		{
			"customer_name": "Terraza 7",
			"service_address": "40-19 Gleane St",
			"service_city": "Queens",
			"service_zip": "11373",
			"latitude": 40.7459,
			"longitude": -73.8783,
			"job_type": JobType.DISCONNECT,
			"required_skills": ["disconnect"],
			"route_criteria": "QN-CENTRAL",
			"priority": 5,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 30,
			"description": "Remove old DJ rig — venue going live-band-only",
		},

		# ─── BRONX — SOUTH (5 jobs) ───
		{
			"customer_name": "Bronx Music Hall",
			"service_address": "438 E 163rd St",
			"service_city": "Bronx",
			"service_zip": "10451",
			"latitude": 40.8265,
			"longitude": -73.9120,
			"job_type": JobType.INSTALL,
			"required_skills": ["install", "maintenance"],
			"route_criteria": "BX-SOUTH",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 90,
			"description": "Install new in-ear monitor system for resident ensemble",
		},
		{
			"customer_name": "Pregones Theater",
			"service_address": "571 Walton Ave",
			"service_city": "Bronx",
			"service_zip": "10451",
			"latitude": 40.8245,
			"longitude": -73.9270,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair", "maintenance"],
			"route_criteria": "BX-SOUTH",
			"priority": 2,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 60,
			"description": "Lighting board fader bank — channels 9-16 stuck",
		},
		{
			"customer_name": "Hostos Center for the Arts",
			"service_address": "450 Grand Concourse",
			"service_city": "Bronx",
			"service_zip": "10451",
			"latitude": 40.8175,
			"longitude": -73.9270,
			"job_type": JobType.SERVICE_CHANGE,
			"required_skills": ["service_change"],
			"route_criteria": "BX-SOUTH",
			"priority": 1,
			"scheduled_date": today,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 120,
			"description": "Replace main hall console — major upgrade",
			"special_instructions": "Coordinate with facilities — power upgrade required",
		},
		{
			"customer_name": "Bronx Opera",
			"service_address": "1130 Grand Concourse",
			"service_city": "Bronx",
			"service_zip": "10456",
			"latitude": 40.8295,
			"longitude": -73.9210,
			"job_type": JobType.INSPECTION,
			"required_skills": ["inspection"],
			"route_criteria": "BX-SOUTH",
			"priority": 3,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Annual rigging + electrical safety inspection",
		},
		{
			"customer_name": "Lehman Center for the Performing Arts",
			"service_address": "250 Bedford Park Blvd W",
			"service_city": "Bronx",
			"service_zip": "10468",
			"latitude": 40.8730,
			"longitude": -73.8930,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance"],
			"route_criteria": "BX-SOUTH",
			"priority": 4,
			"scheduled_date": today,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 60,
			"description": "Monthly PM — house left + center clusters",
		},

		# ─── TOMORROW — Light load (5 jobs, for day-picker demo) ───
		{
			"customer_name": "Knockdown Center",
			"service_address": "52-19 Flushing Ave",
			"service_city": "Queens",
			"service_zip": "11378",
			"latitude": 40.7150,
			"longitude": -73.9080,
			"job_type": JobType.INSTALL,
			"required_skills": ["install", "service_change"],
			"route_criteria": "QN-CENTRAL",
			"priority": 2,
			"scheduled_date": tomorrow,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 120,
			"description": "Main hall — new line array hang",
			"special_instructions": "Lift required — book in advance",
		},
		{
			"customer_name": "Roulette Intermedium",
			"service_address": "509 Atlantic Ave",
			"service_city": "Brooklyn",
			"service_zip": "11217",
			"latitude": 40.6852,
			"longitude": -73.9789,
			"job_type": JobType.REPAIR,
			"required_skills": ["repair"],
			"route_criteria": "BK-WEST",
			"priority": 3,
			"scheduled_date": tomorrow,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 60,
			"description": "Recording feed dropout — trace from console to ISO room",
		},
		{
			"customer_name": "Nuyorican Poets Cafe",
			"service_address": "236 E 3rd St",
			"service_city": "New York",
			"service_zip": "10009",
			"latitude": 40.7227,
			"longitude": -73.9810,
			"job_type": JobType.MAINTENANCE,
			"required_skills": ["maintenance"],
			"route_criteria": "MN-DOWNTOWN",
			"priority": 4,
			"scheduled_date": tomorrow,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 45,
			"description": "Mic locker — clean and re-wind cables",
		},
		{
			"customer_name": "Marcus Garvey Park Amphitheater",
			"service_address": "18 Mt Morris Park W",
			"service_city": "New York",
			"service_zip": "10027",
			"latitude": 40.8035,
			"longitude": -73.9445,
			"job_type": JobType.INSPECTION,
			"required_skills": ["inspection"],
			"route_criteria": "MN-HARLEM",
			"priority": 3,
			"scheduled_date": tomorrow,
			"time_slot_start": "08:00",
			"time_slot_end": "12:00",
			"estimated_duration": 45,
			"description": "Pre-season outdoor stage inspection",
		},
		{
			"customer_name": "Bargemusic",
			"service_address": "Fulton Ferry Landing",
			"service_city": "Brooklyn",
			"service_zip": "11201",
			"latitude": 40.7032,
			"longitude": -73.9968,
			"job_type": JobType.SERVICE_CHANGE,
			"required_skills": ["service_change"],
			"route_criteria": "BK-WEST",
			"priority": 2,
			"scheduled_date": tomorrow,
			"time_slot_start": "12:00",
			"time_slot_end": "17:00",
			"estimated_duration": 90,
			"description": "Replace house mics — saltwater corrosion",
			"special_instructions": "Floating venue — schedule around tide",
		},
	]


async def seed_all():
	"""Drop existing data and seed fresh."""
	await init_db()

	async with AsyncSessionLocal() as session:
		print("\n🎷 Seeding FieldOpt with jazz data...\n")

		# Clear existing data (order matters — assignments first)
		from sqlalchemy import text
		await session.execute(text("DELETE FROM assignments"))
		await session.execute(text("DELETE FROM jobs"))
		await session.execute(text("DELETE FROM technicians"))
		await session.commit()
		print("  ✓ Cleared existing data")

		# Seed technicians
		for tech_data in TECHNICIANS:
			tech = Technician(
				**tech_data,
				current_latitude=tech_data["home_latitude"],
				current_longitude=tech_data["home_longitude"],
			)
			session.add(tech)
		await session.commit()
		print(f"  ✓ {len(TECHNICIANS)} technicians seeded")

		# Seed jobs — redistribute today's jobs across 1-hour slots so the
		# demo timeline reads naturally (8:00-9:00, 9:00-10:00, …). Lunch
		# hour (12-13) is skipped so techs aren't dispatched during break.
		jobs_data = make_jobs()
		_today = datetime.now(timezone.utc).replace(hour=8, minute=0, second=0, microsecond=0)
		_HOURS = ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00", "15:00", "16:00"]
		_idx = 0
		for job_data in jobs_data:
			if job_data.get("scheduled_date") == _today:
				h = _HOURS[_idx % len(_HOURS)]
				next_h = f"{int(h[:2]) + 1:02d}:00"
				job_data["time_slot_start"] = h
				job_data["time_slot_end"] = next_h
				_idx += 1
			job = Job(**job_data)
			session.add(job)
		await session.commit()
		print(f"  ✓ {len(jobs_data)} jobs seeded")

		print("\n🎵 Done! All jazz, all day.\n")


if __name__ == "__main__":
	asyncio.run(seed_all())
